---
- name: Converge
  hosts: all
  tasks:
    - name: Include microk8s
      ansible.builtin.include_role:
        name: microk8s
  vars:
    microk8s_user: 'microk8s_user'
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
